site_name: AFMussap Tech EveryPill Reminder
pages:
- About: 'index.md'
- Sign in: 'signin.md'
- Main menu: 'main_menu.md'
- Features:
   - Medicines: 'medicines.md'
   - Calendar: 'calendar.md'
   - Friends: 'friends.md'
   - Chat: 'chat.md'
theme: readthedocs
site_favicon: images/favicon.ico
google_analytics: ['UA-45971598-3', 'auto']
markdown_extensions:
- pymdownx.admonition
- pymdownx.mark
- pymdownx.magiclink
- pymdownx.critic